version: '3'

services:
  angular-app:
    image: nginx:latest
    container_name: angular-app
    ports:
      - "8080:80"  # Map port 8080 on host to port 80 on container
    volumes:
      - ./dist:/usr/share/nginx/html  # Mount the Angular app build output directory to NGINX's web root directory
    restart: always  # Restart the container automatically if it stops for any reason
